services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud_app
    restart: unless-stopped
    ports:
      - "${NEXTCLOUD_PORT}:80"
    environment:
      # Usando o serviço postgres da stack postgres.yaml
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.localhost localhost ${NEXTCLOUD_TRUSTED_DOMAINS}
      - OVERWRITEPROTOCOL=https

    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - local-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.localhost`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

volumes:
  nextcloud_data:

networks:
  local-network:
    external: true
